spring.application.name=parameter-service
server.port=8083

# PostgreSQL Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/parameter_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.liquibase.change-log=classpath:db/changelog/master.xml